# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0676540cf05c4271c4ffc618e5ed3f3f054cbeec2604ae351462d0ed52901a4cbbcf1e9840ebc45919e56bbd32bdcd4913f2c8c54bf74880ad8394a173fdcc2b

test:
  secret_key_base: 460415a14b1e2a5157cd4d898cc11970befd7bbd45ce6067d19e229d4f3b23ee2fcbe8eef280268b2d6ed06cf94a25b4618fa617f8baf81997e0054ff15e0f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
